// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://phqwdiaixmwtfhvmbthr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBocXdkaWFpeG13dGZodm1idGhyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgxMDQxNjYsImV4cCI6MjA1MzY4MDE2Nn0.BbruO7b9IPSxJUsV0_hGuvOTFC3egmkCfFiiW3YiR1U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);